# Generated by Django 2.2 on 2019-03-25 08:09

from django.db import migrations, models
import django.db.models.deletion
import multipleselectionfield.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class_Name', models.CharField(max_length=8)),
                ('Number_Of_Students_In_Class', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_fees_status', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Fees',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(default=False, upload_to='image')),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('Date_of_birth', models.DateField(default=True)),
                ('Address', models.CharField(max_length=500)),
                ('sex', multipleselectionfield.db.fields.MultipleSelectionField(choices=[(1, 'male'), (2, 'female')], default=None, max_length=3, null=True)),
                ('Guardians_Phone_Number', models.CharField(max_length=11)),
                ('Current_class', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='secondary.Class')),
                ('PaidTuition', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='secondary.Fees')),
            ],
            options={
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject_name', models.CharField(max_length=300)),
                ('Class_allocated', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='secondary.Class')),
            ],
            options={
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=250)),
                ('Last_Name', models.CharField(max_length=250)),
                ('Sex', multipleselectionfield.db.fields.MultipleSelectionField(choices=[(1, 'male'), (2, 'female')], max_length=3, null=True)),
                ('Phone_Number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Address', models.CharField(max_length=500)),
                ('Qualification', models.CharField(max_length=300)),
                ('Admin_Role', multipleselectionfield.db.fields.MultipleSelectionField(choices=[(1, 'Proprietor'), (2, 'Vice principal'), (3, 'Dean'), (4, 'ICT Director'), (5, 'Class Teacher')], default=None, help_text="what's your position in the school", max_length=9, null=True)),
                ('Photo', models.ImageField(default=None, upload_to='media/users/%Y/%m/%d/')),
                ('State_of_origin', models.CharField(default=None, max_length=100)),
                ('Subjects_Handling', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='secondary.Subjects')),
            ],
            options={
                'verbose_name_plural': 'Teachers',
            },
        ),
    ]
