# Generated by Django 2.2 on 2019-03-25 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0003_auto_20190325_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Gender',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='secondary.Gender'),
        ),
    ]
