# Generated by Django 2.2 on 2019-03-25 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0004_auto_20190325_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Gender',
            new_name='Sex',
        ),
    ]
