# Generated by Django 2.2 on 2019-03-25 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0005_auto_20190325_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Sex',
            new_name='Gender',
        ),
    ]
