# Generated by Django 2.2 on 2019-03-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0006_auto_20190325_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='Number_Of_Students_Owing_Outstanding_Debt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='Number_Of_Students_That_Have_Paid_Fees',
            field=models.IntegerField(default=0),
        ),
    ]
