# Generated by Django 2.2 on 2019-03-26 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0007_auto_20190326_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='Number_Of_Students_That_Have_Paid_Fees',
        ),
    ]
