# Generated by Django 2.2 on 2019-03-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0009_auto_20190326_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='Number_Of_Students_In_Class',
            field=models.IntegerField(default=0),
        ),
    ]
