# Generated by Django 2.2 on 2019-01-14 07:31

from django.db import migrations, models
import django.db.models.deletion
import multipleselectionfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elementary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Elementary_Name', models.CharField(default=False, max_length=8)),
                ('Number_Of_Class_Members', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(default=False, upload_to='image')),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('Date_of_birth', models.DateField(default=True)),
                ('Address', models.CharField(max_length=500)),
                ('sex', multipleselectionfield.db.fields.MultipleSelectionField(choices=[(1, 'male'), (2, 'female')], default=1, max_length=3)),
                ('Guardians_Phone_Number', models.CharField(max_length=11)),
                ('PaidTuition', models.BooleanField(default=False)),
                ('NotPaidTuition', models.BooleanField(default=False)),
                ('Present_class', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='primary.Elementary')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject_name', models.CharField(max_length=300)),
                ('Class_allocated', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='primary.Elementary')),
            ],
            options={
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=250)),
                ('Last_Name', models.CharField(max_length=250)),
                ('Sex', multipleselectionfield.db.fields.MultipleSelectionField(choices=[(1, 'male'), (2, 'female')], default=1, max_length=3)),
                ('Address', models.CharField(max_length=500)),
                ('Qualification', models.CharField(max_length=300)),
                ('Admin_Role', multipleselectionfield.db.fields.MultipleSelectionField(choices=[(1, 'Proprietor'), (2, 'Vice principal'), (3, 'Dean'), (4, 'ICT Director'), (5, 'Class Teacher')], default=0, max_length=9)),
                ('Subjects_Handling', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='primary.Subjects')),
            ],
        ),
    ]
