# Generated by Django 2.2 on 2019-02-04 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0002_auto_20190114_0924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pupil',
            options={'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name_plural': 'Teachers'},
        ),
    ]
