# Generated by Django 2.2 on 2019-03-13 18:44

from django.db import migrations
import multipleselectionfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0003_auto_20190204_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='sex',
            field=multipleselectionfield.db.fields.MultipleSelectionField(choices=[(1, 'male'), (2, 'female')], default=None, max_length=3),
        ),
    ]
